import stim
import numpy as np
import pathlib
from ldpc.bposd_decoder import BpOsdDecoder
from functools import partial
import sinter
import beliefmatching
import pymatching
import qldpc

def ilp(matrix):
    decoder = partial(qldpc.decoder.decode_with_ILP, matrix=matrix.check_matrix.toarray())
    def decode(syndrome):
        try:
            return decoder(syndrome=syndrome)
        except:
            return np.zeros(matrix.check_matrix.shape[1], dtype=syndrome.dtype)
    return decode


class CustomDecoder(sinter.Decoder):

    """
    Initializes a CustomDecoder object.

    Args
    ----------
    decoder: A decoder object
    """

    def __init__(self, decoder_function):
        self.decoder_function = decoder_function

    def decode_via_files(
        self,
        *,
        num_shots: int,
        num_dets: int,
        num_obs: int,
        dem_path: pathlib.Path,
        dets_b8_in_path: pathlib.Path,
        obs_predictions_b8_out_path: pathlib.Path,
        tmp_dir: pathlib.Path,
    ) -> None:
        """Performs decoding by reading problems from, and writing solutions to, file paths.
        Args:
            num_shots: The number of times the circuit was sampled. The number of problems
                to be solved.
            num_dets: The number of detectors in the circuit. The number of detection event
                bits in each shot.
            num_obs: The number of observables in the circuit. The number of predicted bits
                in each shot.
            dem_path: The file path where the detector error model should be read from,
                e.g. using `stim.DetectorErrorModel.from_file`. The error mechanisms
                specified by the detector error model should be used to configure the
                decoder.
            dets_b8_in_path: The file path that detection event data should be read from.
                Note that the file may be a named pipe instead of a fixed size object.
                The detection events will be in b8 format (see
                https://github.com/quantumlib/Stim/blob/main/doc/result_formats.md ). The
                number of detection events per shot is available via the `num_dets`
                argument or via the detector error model at `dem_path`.
            obs_predictions_b8_out_path: The file path that decoder predictions must be
                written to. The predictions must be written in b8 format (see
                https://github.com/quantumlib/Stim/blob/main/doc/result_formats.md ). The
                number of observables per shot is available via the `num_obs` argument or
                via the detector error model at `dem_path`.
            tmp_dir: Any temporary files generated by the decoder during its operation MUST
                be put into this directory. The reason for this requirement is because
                sinter is allowed to kill the decoding process without warning, without
                giving it time to clean up any temporary objects. All cleanup should be done
                via sinter deleting this directory after killing the decoder.
        """
        self.dem = stim.DetectorErrorModel.from_file(dem_path)
        self.initialize_decoder()

        shots = stim.read_shot_data_file(
            path=dets_b8_in_path, format="b8", num_detectors=num_dets
        )

        predictions = np.zeros(
            (num_shots, num_obs), dtype=bool)

        for i in range(num_shots):
            predictions[i, :] = self.full_decode(shots[i, :])

        stim.write_shot_data_file(
            data=predictions,
            path=obs_predictions_b8_out_path,
            format="b8",
            num_observables=num_obs,
        )

    def full_decode(self, syndrome: np.ndarray) -> np.ndarray:
        corr = self.decode(syndrome=syndrome)
        return (self.check_matrices.observables_matrix @ corr) % 2

    def initialize_decoder(self):
        self.check_matrices = beliefmatching.detector_error_model_to_check_matrices(self.dem, allow_undecomposed_hyperedges=True)
        self.decode = self.decoder_function(self.check_matrices)
            
