# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]  # these are the defaults, plus ready_for_review
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  install:
    name: Installation check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install package and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev]'

  format:
    name: Linting check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install package and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev]'
      - name: Run ruff format
        run: |
          checks/format_.py
      - name: Run ruff check
        run: |
          checks/lint_.py

  mypy:
    name: Type check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install package and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev]'
      - name: Run mypy
        run: |
          checks/mypy_.py

  coverage:
    name: Pytest and coverage check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 4
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install package and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev]'
      - name: Run coverage
        run: |
          checks/coverage_.py
